version: "3"
services:
  db:
    image: mariadb
    container_name: mydb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Seguro##2022
    volumes:
      - ./data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: admindb
    restart: always
    ports:
      - 8080:8080
   
  miservicio_php:
    image: php:7.4-apache
    container_name: web
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:

      - db

