version: "3"
services:
  db:
    build:
      context: dockerizer/database/.

    container_name: mydb
    ports:
      - 3306:3306
    
    ##volumes:
     ## - ./data/mysql:/var/lib/mysql

    
  adminer:
    image: adminer
    container_name: admindb
    restart: always
    ports:
      - 8081:8080
   
  web:
    build: dockerizer/apache/.
    container_name: web

    expose:
      - 80
    ports:
      - 80:80
    links:

      - db

