version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_USER=papy
      - MYSQL_PASSWORD=dameduro
    volumes:
      # Montamos un volumen para MySQL para no perder los datos de bd
      - ./data/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
   
  miservicio_php:
    image: php:7.4-apache
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./miweb/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - mysql